### ISSUE TITLE
Avoid legacy timestamps?

### ISSUE THREAD

**Issue by phillip-haydon** [serilog-contrib/Serilog.Sinks.Postgresql.Alternative#45]
When I try to log using the suggested columns from the how to.

> Cannot write DateTimeOffset with Offset=08:00:00 to PostgreSQL type 'timestamp with time zone', only offset 0 (UTC) is supported. Note that it's not possible to mix DateTimes with different Kinds in an array/range. See the Npgsql.EnableLegacyTimestampBehavior AppContext switch to enable legacy behavior.

```
    IDictionary<string, ColumnWriterBase> columnWriters = new Dictionary<string, ColumnWriterBase>
    {
        { "message", new RenderedMessageColumnWriter(NpgsqlDbType.Text) },
        { "message_template", new MessageTemplateColumnWriter(NpgsqlDbType.Text) },
        { "level", new LevelColumnWriter(true, NpgsqlDbType.Varchar) },
        { "raise_date", new TimestampColumnWriter(NpgsqlDbType.TimestampTz) },
        { "exception", new ExceptionColumnWriter(NpgsqlDbType.Text) },
        { "properties", new LogEventSerializedColumnWriter(NpgsqlDbType.Jsonb) },
        { "props_test", new PropertiesColumnWriter(NpgsqlDbType.Jsonb) },
        { "machine_name", new SinglePropertyColumnWriter("MachineName", PropertyWriteMethod.ToString, NpgsqlDbType.Text, "l") }
    };
```

How can I just store UTC without time stamps? I don't want to go changing npgsql default behavior on an existing app.

**Comment by SeppPenner** [comment]
Can you test version 3.4.0, please? I have done a simple change to store the values in UTC only, but I'm not really sure if it works on all systems right now (My computer is set to German settings and it seems to work properly).

https://github.com/serilog-contrib/Serilog.Sinks.Postgresql.Alternative/commit/0667bddbd22b9e6bcd91e1e0f4da4a623f24a9f0

**Comment by phillip-haydon** [comment]
Will test it out today, thanks.

**Comment by phillip-haydon** [comment]
I don't get an error, but I don't get any records in the database. So just debugging to see if I messed up or if there's a new bug.

**Comment by SeppPenner** [comment]
Okay, strange. Keep me updated, I will provide a fix once you find anything.

**Comment by SeppPenner** [comment]
Do you already have any results on this issue? :)

**Comment by phillip-haydon** [comment]
I'm so sorry :'(

Just been so busy I haven't touched my personal projects.

I have double checked everything, had to uninstall the packages and reinstall because I messed something up. All the logs are now working 100% correctly without issue.

Can confirm issue is resolved and its working great. Really appreciate you fixing it. And I'm really sorry I took so long to confirm :(

**Comment by SeppPenner** [comment]
> I'm so sorry :'(
> 
> Just been so busy I haven't touched my personal projects.
> 
> I have double checked everything, had to uninstall the packages and reinstall because I messed something up. All the logs are now working 100% correctly without issue.
> 
> Can confirm issue is resolved and its working great. Really appreciate you fixing it. And I'm really sorry I took so long to confirm :(

No problem. I know that and sometimes have more times for the projects here and sometime no time at all...

Glad to hear that it's solved.
