### ISSUE TITLE
Table is not created

### ISSUE THREAD

**Issue by ctindex** [serilog-contrib/Serilog.Sinks.Postgresql.Alternative#50]
I'm trying to log to a postgres database inside a Net 6.0 Console application.   
packages:

~~~xml
	        <PackageReference Include="Serilog" Version="2.11.0" />
		<PackageReference Include="Serilog.Sinks.Console" Version="4.0.1" />
		<PackageReference Include="Serilog.Sinks.File" Version="5.0.1-dev-00947" />
		<PackageReference Include="Serilog.Sinks.Postgresql.Alternative" Version="3.4.2" />
~~~

I copied the [basic usage example](https://github.com/serilog-contrib/Serilog.Sinks.Postgresql.Alternative/blob/master/HowToUse.md) and changed 3 things:  

* added Serilog debugging
* changed connectionstring
* added `needAutoCreateTable` and `schemaName` in the `WriteTo`-Statement

full code:

~~~cs
using System;
using System.Collections.Generic;
using Serilog;
using Serilog.Sinks.PostgreSQL.ColumnWriters;
using NpgsqlTypes;
using Serilog.Sinks.PostgreSQL;

namespace proto_core {
    public static class Program {

        public static void Main() {
            Serilog.Debugging.SelfLog.Enable(msg => Console.WriteLine(msg));
            Serilog.Debugging.SelfLog.Enable(Console.Error);


            string connectionString = "SERVER=192.168.2.121;PORT=5432;DATABASE=myDatabase;USER ID=myUser;PASSWORD=myPassword";


            string tableName = "logs";

            IDictionary<string, ColumnWriterBase> columnWriters = new Dictionary<string, ColumnWriterBase>
            {
                { "message", new RenderedMessageColumnWriter(NpgsqlDbType.Text) },
                { "message_template", new MessageTemplateColumnWriter(NpgsqlDbType.Text) },
                { "level", new LevelColumnWriter(true, NpgsqlDbType.Varchar) },
                { "raise_date", new TimestampColumnWriter(NpgsqlDbType.TimestampTz) },
                { "exception", new ExceptionColumnWriter(NpgsqlDbType.Text) },
                { "properties", new LogEventSerializedColumnWriter(NpgsqlDbType.Jsonb) },
                { "props_test", new PropertiesColumnWriter(NpgsqlDbType.Jsonb) },
                { "machine_name", new SinglePropertyColumnWriter("MachineName", PropertyWriteMethod.ToString, NpgsqlDbType.Text, "l") }
            };

            var logger = new LoggerConfiguration()
                .WriteTo.PostgreSQL(connectionString, tableName, columnWriters, needAutoCreateTable: true, schemaName: "kontrolle")
                .CreateLogger();

            logger.Information("testmessage");
        }
    }
}

~~~

No error or debugmessage is shown. Calling `select * from kontrolle.logs` returns `ERROR: relation "logs" does not exist`. I would expect the table to be created and containing one row with my `testmessage`.  

Could somebody point out what I could be doing wrong?

**Comment by ctindex** [comment]
I found out it was because Sink.PostgreSQL.Alternative uses `PeriodicBatching` which queues the logevents and uses a timer to dequeue and finally log the events.  
Without using `using` or manually call `Dispose` on `Logger` the Program exits befor the queue is processed. So I added `logger.Dispose();` and the table was created and the event successfully logged.

**Comment by SeppPenner** [comment]
> I found out it was because Sink.PostgreSQL.Alternative uses `PeriodicBatching` which queues the logevents and uses a timer to dequeue and finally log the events. Without using `using` or manually call `Dispose` on `Logger` the Program exits befor the queue is processed. So I added `logger.Dispose();` and the table was created and the event successfully logged.

I will add this to the documentation :)

**Comment by SeppPenner** [comment]
Hint is added under https://github.com/serilog-contrib/Serilog.Sinks.Postgresql.Alternative/blob/master/HowToUse.md#hints.

**Comment by douglasg14b** [comment]
@SeppPenner This is still unclear. There is no `Log.CloseAndFlush();` on a logger instance as the instructions say.

Should we still be using `Log.Logger.Dispose()`? This seems undesirable, if we are disposing our logging instance...?

**Comment by SeppPenner** [comment]
I got a request, but only per mail? No idea how this happened...:

> This is still unclear. There is no Log.CloseAndFlush(); on a logger instance as the instructions say.

> Should we still be using Log.Logger.Dispose()? This seems undesirable, if we are disposing our logging instance...?

The answer is simple: The `Log.CloseAndFlush();` is a static method from the static Serilog `Log` context that works independent of the logger instance you create. I still don't really understand why this is necessary though...
