### ISSUE TITLE
Custom Field Does Not Populate

### ISSUE THREAD

**Issue by waldenltd** [serilog-contrib/Serilog.Sinks.Postgresql.Alternative#51]
Hello,

I have been using the Serilog MSSQL sink for awhile with great success.  A decision was made to instead use the Serilog Postgres sing.

Using the example below I was able to successfully create the table and log records.  Unfortunately, I was not able to populate the field TestColumnName.  It is always null.  I used the same code as in the MSQL sink which is shown below.  Is it possible to achieve this?

   LogContext.PushProperty("TestColumnName", "test" , false);
   LoggerTypes.AuditConfiguration.Information("Testlog");

{
  "Serilog": {
    "LevelSwitches": {
      "$controlSwitch": "Verbose"
    },
    "MinimumLevel": {
      "ControlledBy": "$controlSwitch"
    },
    "WriteTo": [
      {
        "Name": "PostgreSQL",
        "Args": {
          "connectionString": "User ID=postgres;Password=postgres;Host=localhost;Port=5432;Database=Serilog;",
          "tableName": "TestLogs",
          "schemaName": null,
          "needAutoCreateTable": true,
          "loggerColumnOptions": {
            "Id": "IdAutoIncrement",
            "TimeStamp": "Timestamp",
            "LogEvent": "LogEvent"
          },
          "loggerPropertyColumnOptions": {
            "TestColumnName": {
              "Name": "TestProperty",
              "Format": "{0}",
              "WriteMethod": "Raw",
              "DbType": "Text"
            }
          },
          "period": "0.00:00:30",
          "batchSizeLimit": 50
        }
      }
    ]
  }
}

**Comment by waldenltd** [comment]
I was able to resolve my issue.  

Thank you for creating this project

**Comment by SeppPenner** [comment]
> I was able to resolve my issue.
> 
> Thank you for creating this project

Sorry for the late reply. Great to hear that. What was the issue?
