### ISSUE TITLE
Partitioning Logs by Date Range

### ISSUE THREAD

**Issue by tngo8** [serilog-contrib/Serilog.Sinks.Postgresql.Alternative#53]
I would love to have the ability to config the table as a partitioned table and put logs into each partition by date or date range as deleting the log partitions would be almost instant and less CPU intensive then deleting log rows.

**Comment by SeppPenner** [comment]
I would recommend https://docs.timescale.com/timescaledb/latest/ for that. It already has suche features including time range queries and stuff like that as well for data retrieving.

As an example, the following needs to be done:
1. Install timescaledb from binary following the instructions under https://docs.timescale.com/install/latest/self-hosted/.
2. Restart your Postgres database.
3. Enable the extension on your logging database, `CREATE EXTENSION IF NOT EXISTS timescaledb CASCADE;`
4. Create your log table, e.g.
```sql
CREATE TABLE IF NOT EXISTS public."Logs1"
(
    "Message" text,
    "MessageTemplate",
    "Level" character varying(50),
    "RaiseDate" timestamp with time zone,
    "Exception" text,
    "Properties" jsonb,
    "PropertyTest" text,
    "IntPropertyTest" integer,
    "MachineName" text
)
```
6. Create the timescaledb hypertable: `SELECT create_hypertable("Logs1", 'RaiseDate');`
7. Create a compund index if you need another one: `CREATE INDEX ON "Logs1" ('RaiseDate' DESC, 'Level');`

**Comment by tngo8** [comment]
Thanks for the suggestion. I wonder if you could extend your function to when the table is first time created (i.e when the Emit function is first call) so that I can actually override the creation to suit my need. The reason is because In my project, at the time of setting up serilog my database connection is probably not ready and I don't want to execute any raw SQL query at that time.

**Comment by SeppPenner** [comment]
Let me think on this, I guess I can include something like that in one of the next releases.

**Comment by tngo8** [comment]
Thank's a lot for your consideration.

**Comment by SeppPenner** [comment]
Sorry, long time... I need to check this again, should be possible.

**Comment by SeppPenner** [comment]
I added a callback in https://github.com/serilog-contrib/Serilog.Sinks.Postgresql.Alternative/commit/980b938ea470de4d1fdba71df0667fab29af53fa and https://github.com/serilog-contrib/Serilog.Sinks.Postgresql.Alternative/commit/323d2bfab94df692ef6b95f257cae6408926e13c. There, you can specify what to do when the schema / table normally would get created. Check out https://github.com/serilog-contrib/Serilog.Sinks.Postgresql.Alternative/blob/master/HowToUse.md#configuration-options, please.
