### ISSUE TITLE
How to order table columns in JSON file?

### ISSUE THREAD

**Issue by pedrooV2** [serilog-contrib/Serilog.Sinks.Postgresql.Alternative#57]

**Comment by cremor** [comment]
@SeppPenner I've also noticed that the column order defined in the JSON setting `loggerColumnOptions` is ignored. It seems like the columns are always created in alphabetical order.
It would be great if this could be improved, either by preserving the order from the JSON file, or by adding an explicit order setting.

**Comment by SeppPenner** [comment]
> @SeppPenner I've also noticed that the column order defined in the JSON setting `loggerColumnOptions` is ignored. It seems like the columns are always created in alphabetical order. It would be great if this could be improved, either by preserving the order from the JSON file, or by adding an explicit order setting.

I need to check that once again.

**Comment by SeppPenner** [comment]
I have created a test, this definitely doesn't work. Will try to fix it now.

**Comment by SeppPenner** [comment]
Should work with the latest changes in V4.0.1, checkout the added test or the how to use file https://github.com/serilog-contrib/Serilog.Sinks.Postgresql.Alternative/blob/master/HowToUse.md (BREAKING change)
