### ISSUE TITLE
Deleting logs older than

### ISSUE THREAD

**Issue by JustSxm** [serilog-contrib/Serilog.Sinks.Postgresql.Alternative#59]
Hello,

When logging with Serilog using files it is possible to retain only a number of files if I'm not mistaken. Is it possible to do something similar with this sink by only keeping for example, the last 24hours only? Or do I need to make something who delete logs every day? Thanks

**Comment by MichalNemec** [comment]
why is this closed? i cannot see any option for this.

**Comment by JustSxm** [comment]
We decided to opt for another option, so I just closed the issue as it doesnt seems as serilog had this as a goal

**Comment by SeppPenner** [comment]
> why is this closed? i cannot see any option for this.

There is none yet, I honestly missed the issue by that time...

**Comment by SeppPenner** [comment]
> We decided to opt for another option, so I just closed the issue as it doesnt seems as serilog had this as a goal

Not Serilog, I just missed it. Still, this is a good idea if you ask me. I'm trying to implement this soon...

**Comment by MichalNemec** [comment]
Hello, is there any update for this?
