### ISSUE TITLE
Why use varchar(50) for level column with Postgres?

### ISSUE THREAD

**Issue by ps30** [serilog-contrib/Serilog.Sinks.Postgresql.Alternative#61]
Question: Why do we need to use **varchar(50)** for only the level column in this PostgreSQL NuGet package?  The other columns are using the more standard type of TEXT which seems to be the modern Postgres go-to for string data.  There is no performance difference between varchar() and TEXT and TEXT can be limited in size with a column constraint.  Is there any problem/reason that we cannot replace the varchar(50) level column with type TEXT when using this NuGet package?

<img width="239" alt="image" src="https://github.com/serilog-contrib/Serilog.Sinks.Postgresql.Alternative/assets/12287002/35908bfe-75de-485f-8a68-21d91c13bc68">

**Comment by SeppPenner** [comment]
Good question, and I have no idea to be honest... :D Will check that.

**Comment by SeppPenner** [comment]
Version 4.0.0 changes that and should be available soon on nuget.org.
