### ISSUE TITLE
not working with we with Npgsql.EntityFrameworkCore

### ISSUE THREAD

**Issue by fares187** [serilog-contrib/Serilog.Sinks.Postgresql.Alternative#63]
it give me this error related to Npgsql.EntityFrameworkCore unget package but the backage is fine
`TypeLoadException: Could not load type 'Npgsql.Internal.TypeMapping.IUserEnumTypeMapping' from assembly 'Npgsql, Version=8.0.0.0, Culture=neutral, PublicKeyToken=5d8b90d52f46fda7'.`
there is no mapping issue in old versions ,version 3.4.1 worked for me but version 4.0.0 , 4.0.1 , 4.0.2 didn't
but even though it still logging the error I found error
`TypeLoadException: Could not load type 'Npgsql.Internal.TypeMapping.IUserEnumTypeMapping' from assembly 'Npgsql, Version=8.0.0.0, Culture=neutral, PublicKeyToken=5d8b90d52f46fda7'.`
logged in my database

**Comment by SeppPenner** [comment]
This issue occurs when a project or a depending project of yours has a direct or implicit reference to something with Npgsql < 8.0.0. They changed the type handlers somehow. So, if all projects are "under your control", you can just update everything Npgsql related to 8.0.0+. If not, you need to contact the other developers to do so. There's honestly nothing else I can do (Except going down to version 7.x for now which I don't want to to be honest)...

**Comment by SeppPenner** [comment]
Check out e.g. https://github.com/npgsql/efcore.pg/issues/3011 and https://www.npgsql.org/doc/release-notes/8.0.html. From https://github.com/npgsql/efcore.pg/issues/3011#issuecomment-1849763048:

> Unfortunately not - some of the big type mapping changes in Npgsql 8.0 mean that EFCore.PG 7.0 is incompatible with Npgsql 8.0. I'll take a look to see if they can be easily be made compatible, and if not, I'll update the nuget dependency to reflect that.

> In the meantime, you'll have to align major versions.
