### ISSUE TITLE
custom column

### ISSUE THREAD

**Issue by fares187** [serilog-contrib/Serilog.Sinks.Postgresql.Alternative#64]
you can not add custom columns using `loggerPropertyColumnOptions` without it removing all the other columns

**Comment by SeppPenner** [comment]
Er, I need to check that. Do you maybe have an example configuration / code already lying around?

**Comment by fares187** [comment]
it is just the mapping issue the I just find my way with it when downgrading to older version sorry I forget to post the answer under the problem and you set it to be closed and you will fix it
