### ISSUE TITLE
Invalid byte sequence for encoding "UTF8"

### ISSUE THREAD

**Issue by tcartwright** [serilog-contrib/Serilog.Sinks.Postgresql.Alternative#65]
I have custom created a postgres table, and I am trying to write to it via the appsettings.json. When I start the application up, I get the following error in the output window and no logs are written:

> 'PostgresWebapp.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.15\System.Diagnostics.StackTrace.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
2024-02-08T18:08:52.6776976Z 22021: invalid byte sequence for encoding "UTF8": 0x00    at Npgsql.Internal.NpgsqlConnector.ReadMessageLong(Boolean async, DataRowLoadingMode dataRowLoadingMode, Boolean readingNotifications, Boolean isReadingPrependedMessage)
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
   at Npgsql.NpgsqlBinaryImporter.Complete(Boolean async, CancellationToken cancellationToken)
   at Serilog.Sinks.PostgreSQL.SinkHelper.ProcessEventsByCopyCommand(IEnumerable`1 events, NpgsqlConnection connection)
   at Serilog.Sinks.PostgreSQL.SinkHelper.Emit(IEnumerable`1 events)
   at Serilog.Sinks.PostgreSQL.PostgreSqlSink.EmitBatchAsync(IEnumerable`1 events)

Startup.cs
```c#
if (Debugger.IsAttached)
{
	SelfLog.Enable(msg => Debug.WriteLine(msg));
}

var logger = new LoggerConfiguration()
	.ReadFrom.Configuration(builder.Configuration)
	.Enrich.FromLogContext()
	.CreateLogger();

Log.Logger = logger;
```

Table script:
```sql
-- Table: public.TestLogs

DROP TABLE IF EXISTS public."TestLogs";

CREATE TABLE IF NOT EXISTS public."TestLogs" (
    "Id" integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Message" text  COLLATE pg_catalog."default",
    "Level" character varying(100) COLLATE pg_catalog."default",
    "TimeStamp" timestamp with time zone,
    "Exception" text COLLATE pg_catalog."default",
    "LogEvent" jsonb,
    "ClientKey" uuid,
    "CorrelationID" uuid,
    CONSTRAINT "TestLogs_pkey" PRIMARY KEY ("Id")
)
TABLESPACE pg_default;
```

appsettings.json
```json
	"Serilog": {
		"LevelSwitches": {
			"$controlSwitch": "Verbose"
		},
		"MinimumLevel": {
			"ControlledBy": "$controlSwitch"
		},
		"WriteTo": [
			{
				"Name": "PostgreSQL",
				"Args": {
					"connectionString": "Server=sv-log-preprod.postgres.database.azure.com;Port=5432;Database=Logs-Dev;User Id=logs-user;Password=gQ^20tJ9Pxzo;CommandTimeout=30;Timeout=15;",
					"tableName": "TestLogs",
					"schemaName": "public",
					"needAutoCreateTable": false,
					"loggerColumnOptions": {
						"Id": {
							"Name": "IdAutoIncrement"
						},
						"Message": {
							"Name": "RenderedMessage"
						},
						"Level": {
							"Name": "Level"
						},
						"TimeStamp": {
							"Name": "Timestamp"
						},
						"Exception": {
							"Name": "Exception"
						},
						"LogEvent": {
							"Name": "LogEvent"
						}
					},
					"loggerPropertyColumnOptions": {
						"ClientKey": {
							"Name": "ClientKey",
							"Format": "{0}",
							"WriteMethod": "Raw",
							"DbType": "uuid"
						},
						"CorrelationID": {
							"Name": "CorrelationID",
							"Format": "{0}",
							"WriteMethod": "Raw",
							"DbType": "uuid"
						}
					},
					"period": "0.00:00:30",
					"batchSizeLimit": 50
				}
			}
		],
		"Enrich": [ "FromLogContext", "WithMachineName" ]
	}
```

Any idea why this is occuring?

**Comment by tcartwright** [comment]
NVM, I figured out that level is stored as an integer.  The issue is resolved.

However, Would it be possible to add an additional column writer to write the level as a varchar?

**Comment by tcartwright** [comment]
As for my last question, I just decided to add a computed column: 

```sql
CREATE TABLE IF NOT EXISTS public."TestLogs"
(
    "Id" integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "System" VARCHAR(100) COLLATE pg_catalog."default",
    "Message" text COLLATE pg_catalog."default",
    "Level" integer,
    "LevelDesc" varchar(100) GENERATED ALWAYS AS (
		CASE
			WHEN "Level" = 0 THEN 'Verbose'
			WHEN "Level" = 1 THEN 'Debug'
			WHEN "Level" = 2 THEN 'Information'
			WHEN "Level" = 3 THEN 'Warning'
			WHEN "Level" = 4 THEN 'Error'
			WHEN "Level" = 5 THEN 'Fatal'
			ELSE 'Information'
		END
	) STORED,
    "TimeStamp" timestamp with time zone,
    "Exception" text COLLATE pg_catalog."default",
    "LogEvent" jsonb,
    "ClientKey" uuid,
    "CorrelationID" uuid,
    CONSTRAINT "TestLogs_pkey" PRIMARY KEY ("Id")
)
```

**Comment by SeppPenner** [comment]
> NVM, I figured out that level is stored as an integer. The issue is resolved.
> 
> However, Would it be possible to add an additional column writer to write the level as a varchar?

This should be included already if I remind correctly. Let me check...

**Comment by SeppPenner** [comment]
For myself: Check if there is an option to store the level as varchar / text.

**Comment by SeppPenner** [comment]
> NVM, I figured out that level is stored as an integer. The issue is resolved.
> 
> However, Would it be possible to add an additional column writer to write the level as a varchar?

Check out https://github.com/serilog-contrib/Serilog.Sinks.Postgresql.Alternative/blob/master/HowToUse.md#configuration-via-json-file -->
> LevelAsText: Stores the log level as Text.

Or:

```csharp
{ "level", new LevelColumnWriter(true, NpgsqlDbType.Varchar) },
```
