### ISSUE TITLE
Update to Serilog v4, remove reference to Serilog.Sinks.PeriodicBatching

### ISSUE THREAD

**Issue by cremor** [serilog-contrib/Serilog.Sinks.Postgresql.Alternative#71]
From the [Serilog.Sinks.PeriodicBatching readme](https://github.com/serilog/serilog-sinks-periodicbatching): 

> Serilog 4.x and later versions support batching natively. New projects should use Serilog's `IBatchedLogEventSink` and `WriteTo.Sink(IBatchedLogEventSink)`, not this package which is now only maintained for compatibility reasons.

Therefore I suggest to release a new major version of this sink which directly uses `IBatchedLogEventSink` from Serilog and doesn't have a reference to Serilog.Sinks.PeriodicBatching any more.

**Comment by SeppPenner** [comment]
Done with https://github.com/serilog-contrib/Serilog.Sinks.Postgresql.Alternative/commit/9a23a5c8b1afb68a0b5022a031a0c419842f9fec and https://github.com/serilog-contrib/Serilog.Sinks.Postgresql.Alternative/commit/dd282cdd01c694ed586052a023e653d11dda62d1.
