### ISSUE TITLE
.NET framework not supported in version greater than v4.0

### ISSUE THREAD

**Issue by BrettJaner** [serilog-contrib/Serilog.Sinks.Postgresql.Alternative#74]
Hey repo maintainers,

Looks like .NET Standard 2.0 was removed as a targeted framework in v4.0.  I can no longer consume this NuGet package in a net481 host application.  Was there a reason to remove .NET Standard?  Any chance we could add it back or maybe one of the .NET framework versions?

Thanks,
Brett J

**Comment by SeppPenner** [comment]
I have no idea honestly, but added it right back...

**Comment by BrettJaner** [comment]
Thank you, but unfortunately I'm still unable to consume v4.1.0 in my .NET Framework application.  .NET Framework can only reference .NET Standard 2.0, not .NET Standard 2.1.

**Comment by SeppPenner** [comment]
Sorry, my bad. Should be fixed with https://github.com/serilog-contrib/Serilog.Sinks.Postgresql.Alternative/commit/74d5cef2dc7627b70ef565b999c357a86fe0bb3c.

**Comment by SeppPenner** [comment]
4.1.1 is incoming :)

**Comment by SeppPenner** [comment]
Version 4.1.2.0 (2024-12-26) removes support for NetStandard again as Npgsql (Version 9.*) does only support Net6 and Net8 anymore: https://www.nuget.org/packages/Npgsql/9.0.2#supportedframeworks-body-tab.

**Comment by BrettJaner** [comment]
Thanks for the heads up!

**Comment by cremor** [comment]
Version 4.1.2 should have been version 5.0. Removing supported target frameworks is a breaking change and should only happen when the major version number is increased.
